### ISSUE TITLE
When Zoom in in Maps, lines disappear

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1009]
Connection: Offline
Situation: in offline maps
Survey: Emprender rural and urbana
Version: Internal test track 1.10.0-rc2

Steps to reproduce:
1. Go offline and create an Emprender survey.
2. Select any offline map
3. Zoom in to select a more precise location
Result: the lines of the streets disappear

First view with normal view (when clicking on a map):
![Screenshot_2019-07-27-16-13-13.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/5e803bb8-907e-4457-a27b-f9979b38da2d)

View when zooming in:
![Screenshot_2019-07-27-16-13-20.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/89ee8621-ff5f-404d-bef8-30ac1fdf2cee)

**Comment by pA1nD** [comment]
This is becasue we overzoom 3 levels.

We download up to zoomlevel 13. We allow the user to zoom in up to zoom level 16. This works on many places but some might have this problem.
The map provider recommends to overzoom only one level.

We cannot download more zoom-levels as this will download at least 4x the current data.
We could limit the zoom level, so this is less likely to happen but therefore it will not allow users anymore to zoom in so much.
