### ISSUE TITLE
Showing survey version in UI while taking a survey

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/stoplight-mobile#1034]
This is an easy reminder to the client (and useful to us) of the version the user takes a survey at a given moment. We only relally need to show a number somewhere. Maybe near the progress bar on all lifemap pages.

@stacylorraineprendeville We need a design for this.

**Comment by pA1nD** [comment]
I think the correct place would be when "selecting the survey" from the list. A small "Version 23" below the survey name.

@stacylorraineprendeville what do you think?

**Comment by stacylorraineprendeville** [comment]
@pA1nD @Danman7 Just like this
![Screen Shot 2019-08-15 at 09.35.14.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/09b77096-2ec4-4092-a8bc-c4ae12d6b723)

and also in the retro view:
![Screen Shot 2019-08-15 at 09.39.24.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/01beacad-2769-4962-822b-12551ab51f96)
