### ISSUE TITLE
Async storage fails to persist large data

### ISSUE THREAD

**Issue by zommerberg** [FundacionParaguaya/stoplight-mobile#1067]
when we are in d/demo and i decide to restart the app, the surveys are removed.
This is an issue related only to d/demo

We think that this is related to no having enough storage in the app order to store the data.
This can be reproduced only by restarting the app from the developer options.

t/demo ,  d/geco and other accounts cannot reproduce this issue

**Comment by stacylorraineprendeville** [comment]
Would this be useful? https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/fp-psp-server/1020

**Comment by Danman7** [comment]
demo/demo is just a way too large account - too many families and surveys and maps. At this moment, this account has not been accessible for a week. Both getting families and surveys returt 502 Proxy Error. I'm putting this in ice box.
