### ISSUE TITLE
Wrong Date in the D.O.B in the family item.

### ISSUE THREAD

**Issue by zommerberg** [FundacionParaguaya/stoplight-mobile#1176]
In this issue we would like to fix the wrong date in the D.O.B in the family item.

Problem ( As described by ana )
In the family list, below the family name there will be a Birth date, for example 31/DIC/2019.

If I click on one family name to view the family profile, and then I click on the first participant to view the details of that member, the birth date is incorrect by one day. It is shown as 30/DIC/2019.

Please this should also be reviewed if the other members' birthdates are correct.

Solution
We need to review and improve the date conversion we have. After we identify where the date is becoming wrong we will be able to correct it via propper date implementation. We actually convert it a couple of times to the point where it can no longer be read properly.

**Comment by zommerberg** [comment]
Update:
After investigating the issue,i found out the reason we see different dates is because we are formatting the a bit differently. And the reason why we see different date in the D.O.B date and the date in the primary participant screen is because in the DateInput component we are not converting the incoming date into utc ,we convert it directly into unix and we can reproduce this issue if we manually put this date in the familiesList D.O.B component and the DateInput component, they will show different dates for the same value.

**Comment by loorely** [comment]
@zommerberg found this bug again in the family profile. We need to review in our next meeting how to solve it. I'm not sure about the solution.
