### ISSUE TITLE
Add a retake button in the family profile

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1183]
In the first screen of the family profile, there should be a retake button that allows the facilitator to take another survey for that family.

This option should only be available for **Facilitators** and **Admin Facilitators**.

Here's the design link:
https://www.figma.com/file/JPKadypECrRPMgYVoPFXpr/Stoplight-Mobile-App?node-id=55%3A0

Something like this:
![Group 13.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/bd00655c-903e-4e3a-b776-a27438a3f4c1)

**Comment by zommerberg** [comment]
Looks like we need to add a button which is visible only for 'ROLE_SURVEY_TAKER' and 'ROLE_SURVEY_USER_ADMIN’, clicking on the button will do nothing for now. And the final design will be provided by Ana at a later point in time.
