### ISSUE TITLE
Business logic to prefill the last snapshot information

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1185]
Business logic to prefill the last snapshot information BUT it should be without location, socioeconomic, stoplight, pictures and sign.
This means that the only screens that should be prefilled are primary participant and other members screen.

**Comment by zommerberg** [comment]
For this we would need to create a new draft for the same survey , while creating this draft we should  prefill the data from the old draft instead of using an empty draft and after that follow the normal draft taking flow. The prefilling itself should be problematic.
