### ISSUE TITLE
More than 1 syncs in progress when there is only 1 family

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1226]
## Problem

If there is only one family with a sync pending tag, and I click on the "Sync" button more than once, then in the Sync screen there will appear several Syncs in progress even though there is only one family.

**Comment by zommerberg** [comment]
The solution for that would be to disable the "SYNC" button  after clicking on a family that is with status "sync pending". There is no need for it to be clickable. The clicking on the sync causes the whole problem.
