### ISSUE TITLE
Signature Screen Navigation Bug

### ISSUE THREAD

**Issue by zommerberg** [FundacionParaguaya/stoplight-mobile#1236]
# Problem as descirbed by ana 
- If I add a signature in the signature screen, then I continue one screen, then I go back to the signature screen, then I kill the app, open again and resume draft, the draft opens in the Upload Pictures screen.

# Solution
This happens due to the outdated navigation we are currently using. In the Signing screen after signing we navigate to the final screen with .push method, it passes the state, however it doesnt detect properly when we mount and unmount the component.  I can fix it by changing some conditional on when and where we should update the draft screen however i think we should leave this bug until the refactoring with the nevest version of RN, since it includes a new navigation and it  will fix the problem

**Comment by aprojas** [comment]
ok, we can wait after the refactoring.

**Comment by zommerberg** [comment]
duplicate with #1311
