### ISSUE TITLE
Smoke "online" test

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1246]
## Mentor App

- [x] Tomar una encuesta con varias imagenes en modo online. Probar si pasa al estado ``Pendiente`` y de un tiempo luego se sincronizada solo. Las encuestas con imagenes son un poco mas lentas. 

- [x] Tomar una encuesta con imagenes y darle guardar. Mientras esta en estado ``Pendiente`` pasar el telefono a modo avion. La encuesta se debe quedar en estado pendiente y cuando vuelva el internet se tiene que volver a sincronizar solo. 

- [x] Tomar encuesta en modo offline con imágenes. Se tiene que guarrdar en modo ``Pendiente`` y sincronizar cuando tenga internet. Probar tambien sincronizar a mano con la opción ``Sincronización`` en el menu lateral .

- [x] Guardar survey sin imágenes, probar con la encuesta de itaipu y con una encuesta que no tiene la opcion de subida de imágenes. Debe funcionar bien en modo offline y modo online. 

- [ ] Probar sincronizar una encuesta en estado ``Pendiente`` desde la vista de familia. 

- [ ]  Probar tomar una encuesta con imagenes y cerrar la app en medio del proceso de de guardado. 

- [x] Probar tomar una encuesta con muchas imágenes que sumen más de 10M y ver que no deja continuar en la vista de subida de fotos. 

- [ ] Tomar varias encuestas en modo offline y guardar, todas con imágenes. Luego darle internet al telefono y sincronizar de forma manual con la opción ``Sincronización`` 

Para todos los casos verificar que la encuesta se haya creado correctamente bajando el reporte desde psp 

- [x] Ingresar a la lista de familias, hacer clic en una familia, después clic en el boton de retaking. Y tomar toda una encuesta estando online. Verificar si la información previa esta cargada. Terminar la encuesta y que sincronice.

- [x] Ingresar a la lista de familias, hacer clic en una familia, después clic en el boton de retaking. Y tomar toda una encuesta estando OFFLINE. Verificar si la información previa esta cargada. Terminar la encuesta, conectarse a internet y que sincronice.

- [x] Tomar una encuesta de seguimiento, cambiar datos de la primera sección y al terminar ver si sincroniza bien.

- [x] Tomar una encuesta de seguimiento, guardar como borrador en algun punto, volver a retomar borrador y ver si continúa donde te habías quedado.

De todas las veces, verificar si al hacer clic en el perfil de la familia, muestra la información de la última encuesta tomada.

**Comment by loorely** [comment]
@aprojas 

Los casos nuevos  de prueba son:

Tomar encuesta sin imagenes y con imagenes en modo avion. Guardar. Volver a modo online, se debe sincronizar solo y no debe permitir sincronizar manualmente.
Tomar encuesta sin imagen y con imagen en modo online. Se tiene que guardar y no debe mostrar el botón de sincronización manual.
Tomar encuesta con imagen y sin imagen en modo online. Exactamente antes de guardar pasar a modo avion y darle Finish. Al salir del modo avion se tiene que sincronizar solo. Si no se sincroniza luego de unos minutos, tiene que aparecer el botón de sincronización manual
