### ISSUE TITLE
The number in badge does not fit properly

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1275]
The number of members in a family in the badge icon is not fitting properly, in the families list of the Stoplight Mobile.

This happens when the + numbers are higher than number 1.

![Screenshot_20201204-100722_Stoplight Mobile.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/93a22ec8-f9b7-4f14-8840-8f4ac5ac9f9c)

**Comment by Guillecaba** [comment]
Ingresar con el usuario t/demo demo
Tomar una encuesta, en la siguiente pantalla:
![ola](https://user-images.githubusercontent.com/9329111/104050757-dc380c80-51c5-11eb-95a1-bc946239a54b.png)
Ir rellenando el formulario e ir agregando 4 miembros, completar la encuesta y guardar
Luego ir al listado de familias(actualizar la list)
![Listado de familias](https://user-images.githubusercontent.com/9329111/104052102-f541bd00-51c7-11eb-9b5f-9c9f127a5ade.png)
entrar a detalle y ver si el numero se ve de forma correcta
