### ISSUE TITLE
Location with wifi sends me to default map

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1296]
User: encuestador_15
Password: password
Survey: Emprender - Rural
Android version: 8.1.0

Also with any survey with the 
user: t/anatest 
pass: 123456

## Problem
If I am online (with wifi) and I arrive to the location screen, it should show me my current location. It automatically takes me to the default map of that survey. Even though I refresh it with the reload button, it still takes me to the default map and not my live location.

**Comment by zommerberg** [comment]
Hello, the only time I was navigated to the default location was when I had the GPS disabled.
Was your GPS disabled at the time? We could request the user to turn on his GPS when the user open the map
