### ISSUE TITLE
The app crashes in the pictures component

### ISSUE THREAD

**Issue by diegotorrespy** [FundacionParaguaya/stoplight-mobile#1297]
## Description
When a picture is taken with a survey with pics support the app crashes and returns at the home page.

Mode: offline
Android version: 9

![stoplight-mobile-01.jpeg](https://images.zenhubusercontent.com/5c1a3b279be21e037cb696fc/9caa3003-87e5-4bda-8373-80464ca2931a)

**Comment by zommerberg** [comment]
What account and survey did you test? I tried with t/anatest but i didn't crash for me.
