### ISSUE TITLE
Crash when I closed the app in socioeconomic section

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1300]
Survey: Emprender - Rural
User: encuestador_15
Pass: password
Android: 8.1.0

## Problem
I answered all the questions for section `Educación`
THEN I closed the app completeley
THEN when I tried to open the app, it showed an error (red and black page) and then the message "Stoplight Mobile has stopped"
I opened the app again, and the draft, and it took me to the `Datos de la familia` section

**Comment by zommerberg** [comment]
I cant log in in the provided account. I tried to reproduce it on another account but it did not crash.
