### ISSUE TITLE
Snapshot stay in status= Pending if file upload fails in the backend

### ISSUE THREAD

**Issue by loorely** [FundacionParaguaya/stoplight-mobile#1301]
## Problem 

If the file upload request fails in the backend it is impossible to retry the snapshot sync cause it stays in ``pending``. We need to find a way to allow the user to retry the snapshot sync if the backend returns an error. 

### COMMENTS
- Try to reproduce this issue and see what happens, and then needs to be done.

### Steps to reproduce:
1. Take a survey with upload images option
Survey: Itaipu
2. Just before saving the draft, put down your local server to see what happens
3. Observe

**Comment by Guillecaba** [comment]
Now, when sending a snapshot with images and the server is out of service, it remains in a Sync Error state allowing it to be sent back
