### ISSUE TITLE
Checkbox answers are not being saved

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1313]
Env: testing
User: t/anatest
Pass: 123456
Survey: Ecuador - Semáforo, Finca
Survey: Ecuador - Semáforo Agroproductivo

## Problem
If I select an answer or several in the checkboxes section, then I finish the survey and then I download the report in the web. I cannot see the answers saved in the excel report.

**Comment by zommerberg** [comment]
I double checked. We are always sending the Data from the checkboxes to the server.
