### ISSUE TITLE
Add "Update list" button in family list

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1354]
- When a user clicks on the update button, a loading animation should appear and the button should be inactive.
- When the update finishes, the number of families will be updated, and the button will still be green.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/02bba702-306d-42be-93b0-37778a57c76b)

**Comment by Guillecaba** [comment]
Además de lo citado mas arriba verificar que al no haber conexión de internet no se debe mostrar el icono de actualizar.

**Comment by Auxi9** [comment]
tested. everything ok.
