### ISSUE TITLE
Priority modal for Family Profile (synced)

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1366]
Reuse priority modal in Family Profile to create priorities AFTER having finished the survey.

-- This design will be for synced families.
-- When clicking on the button "Add new priority", there should be a new screen with only reds and yellows. And when the user clicks on any red or yellow indicator, the priority modal appears.

-- When a user sends a priority, a request should go on a list

**Comment by Guillecaba** [comment]
Por el modal se refiere a esto:

![Listado de familias](https://user-images.githubusercontent.com/9329111/104057601-325e7d00-51d1-11eb-9702-a4bd92cf924f.png)

 listado de familias -> detalle de familia -> tab Stopligth -> Boton Add Priority -> Click en un indicador que no tenga ya el simbolo de Pin(ya es una prioridad)
