### ISSUE TITLE
Handle priority sync state 

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1379]
Handle priority sync state

- When a priority is pending synchronization, there should be a label next to the indicator name "Priority pending", and the priority icon should appear in the red/yellow circle when the priority has finished syncing.
- If there is time, add a gray icon in the red/yellow circle when the priority has not synced yet. 
- When a priority synchronization fails, it should appear in the sync tab, with a new label identifying the error "The new priority has failed to upload."
Change to: Priority sync error

**Comment by Guillecaba** [comment]
El proceso descripto en  #1366  Y #1378 debe poder realizarce offline, la lista de prioridades pendientes debe ser visible en la pantalla que se accede desde el acceso de Sync
![inferior](https://user-images.githubusercontent.com/9329111/104059525-422b9080-51d4-11eb-8e6a-69afdbfbea1a.png)
y se debe cumplir lo dicho en la descripción del issue mas arriba
