### ISSUE TITLE
Create new list of red/yellow indicators

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1380]
When a user clicks on "Add priority", it should just show a screen with yellow and red indicators.
Then click on an indicator and the priority modal appears.
The user can create more than one priority.
There should be a final button at the bottom, that says "Finish".
After clicking on Finish, should take you to the Family profile Stoplight screen, and show the new labels/icons.

**Comment by Guillecaba** [comment]
user guille 123456
ir a listado de familias -> detalle de familia -> tab Stopligth -> Boton Add Priority 
Luego continuar con lo escrito en la descripción del issue
