### ISSUE TITLE
Add total of indicators at end of survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1381]
![image.png](https://images.zenhubusercontent.com/5c9ced779a9dfd5292735bfa/0a7ed1ea-e93e-4e2b-8fc1-41c32b8eda61)

The color icons should appear closer together and  with their total  number

Something like this:

![Total count of indicators.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/daa275b1-a5f3-41f3-b214-95519cd828c4)

**Comment by Guillecaba** [comment]
user: t/demo demo
Tomar una encuesta, luego de haber completado el semáforo, y luego del mapa, se visualiza esta pantalla
El tamaño de los circulos son iguales entre si a diferencia del diseño mostrado en la descripción del issue
