### ISSUE TITLE
Login improvement 

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1393]
As of this moment when an user closes the app when maps or images are being downloaded  the app it's left unusable. In order to avoid this issue we need to make sure we kill all processes when closing the app.

**Comment by Guillecaba** [comment]
Apuntar al backend de testing
marcar la opción de descargar mapas en el login
Ingresar con el usuario t/anatest 123456
al comento que este descargando los mapas antes que se complete cerrar la aplicacion
Luego volver a abrir la aplicacion y la descarga de mapas de continuar,
antes al realizar esto, si se cerraba la app al momento de 2/7 descargas de mapas y luego se abria la app se tomaba como si las 7 ya se descargaron pero esto era un error

**Comment by Auxi9** [comment]
Tested. Everything ok.

**Comment by Auxi9** [comment]
Mi prueba fue: 
1. Estar conectada a internet
2. Hacer login
3. Al momento de estar descargando los mapas salir de la app. 
4. Volver a ingresar continuo de manera correcta la descarga de mapas
5. Luego de esto la aplicacion se quedo colgada. 
En la pantalla de la app se visualizaba 
_mapas sincronizadas    ok(icono del check)
calculando imagenes a sincronizar._
