### ISSUE TITLE
Handle lack of access to a family's original survey

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1400]
As of now when a facilitator loses access to a survey and has families with that survey, when he tries to view  an old family the app crashes

**Comment by Guillecaba** [comment]
Apuntar al app al backend de testing
Ingresar con el usuario t/guille 123456, podes desmarcar las opciones para desarrollador
Tomar una encuesta, por comodidad puede ser la que diga Stoplight Demo y guardar una vez completado
Ir al listado de familias (recordar refrescar la pantalla)
Ingresar al detalle de la familia que habías tomado la encuesta
Todos los datos deben poder visualizarse en ambos tabs
Ahora vamos a desvincular al usuario del survey con el que se tomo la encuesta, para eso vamos a la plataforma web e ingresamos con el usuario hub y pass hub y vamos al tab de encuestas, donde vamos al listado de encuestas y desactivamos la organización a la que pertenece el usuario con el que tome la encuesta y guardamos.
Ahora volvemos a la app, y deslogeamos el usuario y borramos todos los datos que tiene en memoria, para ahora logear de vuelta.
Volvemos a ir a la pantalla de familias e ir al detalle de familia no debe ocurrir ningún crash, el cual se producia al no contar mas el usuario con el survey con el que se tomo la encuesta, y lo

**Comment by Auxi9** [comment]
Tested. Everything OK.
