### ISSUE TITLE
Add "see password" option

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1404]
Enable the "see password" option with the eye icon when logging in the app, so users can see or unsee the password they are typing in.

**Comment by Guillecaba** [comment]
have to invert icons

**Comment by Guillecaba** [comment]
Go to login 
![Screenshot_1611152160](https://user-images.githubusercontent.com/9329111/105186948-ff8d8080-5b10-11eb-9416-db6e1727a19d.png)
![Screenshot_1611152164](https://user-images.githubusercontent.com/9329111/105187023-10d68d00-5b11-11eb-9a0b-f494bc957fe5.png)
