### ISSUE TITLE
Restyle the width on some devices

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1406]
When Hugo was clicking on the logout options, the modals covered the complete padding on the left and right.

Device:
Huawei p30 lite
6,15" IPS/LCD FullHD+ (2.312 x 1.080 píxeles)

**Comment by Guillecaba** [comment]
Login with t/guille 123456
![Screenshot_1611154147](https://user-images.githubusercontent.com/9329111/105195528-7cbcf380-5b19-11eb-970c-482e67df5359.png)

Toma una encuesta y guardar como draft, al tratar de hacer logout el modal no debe ocupar el total del ancho

**Comment by Auxi9** [comment]
Para el celular galaxy J1 ace el modal agarra toda la pantalla. version android 5.1

**Comment by Auxi9** [comment]
no agarra todo la pantalla y el texto se estira de manera vertical creando un scroll innecesario @aprojas 
![image (13).png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/8f9e41e0-91b9-4148-8378-7888091b99b5)
