### ISSUE TITLE
ITT priority bug

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1414]
When I finish adding priorities in the family profile, and then go back to the Life Map screen, I click on the indicator I just prioritized to see what I wrote, and the modal is not showing all the info. Also, the filter is not being updated. The little blue pins should appear in the total count.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/fee471ed-e031-490d-b1fa-a88cfd458f26)

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/06625237-8d0b-4afa-ad92-abf78a63e4c7)

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/300588d0-fe7d-4519-b06a-9b2d5d31ee32)

**Comment by Guillecaba** [comment]
Login con t/guille 123456
Entrar al listado de familias
Seleccionar una familia que tenga indicadores en amarillo o rojo
Agregar prioridad
guardar la prioridad
Al volver a la vista de stopligth del perfil
Debe actualizarse con un punto azul el resumen visual de indicadores
en el listado de indicadores al filtrar prioridades debe aparecer los recien agregados
