### ISSUE TITLE
Fix  warnings  that appear  in console

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1417]
Check: Families list, dashbaord and family profile.

**Comment by aprojas** [comment]
1. I found that when you click on the family from the main page, like the draft, it does not show the complete family name on the top.
@Guillecaba 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/dcfc5b58-1b47-4eb5-b42a-f417d8e1bf17)
