### ISSUE TITLE
Save single draft button

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1425]
- Incluir un botón de sincronizar por draft  en estado pendiente en el dashboard ( si es que hay conexión)
- Cuando el usuario haga clikc en el botón  con el draftId   buscar en la cola de redux offline las llamadas correspondientes al  draf ( el botón debe quedar bloqueado y con una aminación de loading)
- Los requests deben ser  hechos por fuera de la cola de redux offline 
  Investigar si se puede esperar la respuesta del servidor
- Si los requests tuvieron exito marcar el draft como  sincronizado el dashboard

**Comment by Auxi9** [comment]
El boton para actualizar creo que deberia quedar alineado. ![screenshot_2.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/7fda4a60-62bc-4fa3-8f1c-a635948aec55)
