### ISSUE TITLE
Gender in family profile in other members is not correct

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1438]
When I want to see the information on other members in a Family Profile, the text of the Gender is not correct.

For example: in the survey of Itaipu which is in SPANISH, it shows the gender in ENGLISH. This only happens to other members, not to the main member. 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/b3a6418c-a024-4488-9d67-93404f7d4752)

**Comment by Auxi9** [comment]
no se soluciono el problema @aprojas
 ![Screenshot_2021-02-16-16-31-28.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/900892f0-9af8-458d-9ab2-e3c93e8bbf71)
