### ISSUE TITLE
Download drafts as a file

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1443]
Research  if it's possible to download redux store data to a device as a file

**Comment by aprojas** [comment]
Al terminar de descargar, debería aparecer una notificación de que terminó de descargar y que puede buscar en la carpeta de "Descarga".

@Guillecaba

**Comment by aprojas** [comment]
Español: "¡La descarga ha terminado! Podrás encontrar el archivo en la carpeta **Download**."
English: "The download has finished! You can find the file in the folder **Download**."
