### ISSUE TITLE
Research ways of allocating ram memory

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1448]
Problem: For older devices the app crashes  because lack of memory ram. Check what we can do to prevent this.

**Comment by Guillecaba** [comment]
Una posible opcion es:
android:largeHeap="true" el cual se agrega en el Android Manifest
sirve para que el proceso de la aplicacion sera creado o no con mayor cantidad de ram, aunque esto tampoco es una garantia ya que el telefono ya puede tener limitada su cantidad de memoria

Link a consejos en stackoverflow: https://stackoverflow.com/questions/27396892/what-are-advantages-of-setting-largeheap-to-true

Documentación: https://developer.android.com/guide/topics/manifest/application-element

Resultados empiricos a travez de android profiling:

Pixel 4: Con 4gb de memoria ram y un uso de aproximadamente 30 minutos, el consumo de memoria va creciendo de manera progresiva, podria ocurrir el caso de un memory leak,
aunque tambien puede ser el comportamiento normal del sistema operativo al tener la posibilidad de asignar mas memoria

Nexus S: le asigne 512mb , al inicial la aplicacion consume aproximadamente 120mb llegando a un pico de 180mb luego de 20 minutos de uso, para luego quedar estable en valores aproximados
