### ISSUE TITLE
Add sync manual button

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1449]
Caso 1  Encuesta con imágenes: Primero debe aparecer un botón para guardar el draft una vez que el draft se haya guardado exitosamente se deberá mostrar un botón para sincronizar las imágenes, si el sincronizado de imágenes falla se deberá dejar el draft en un nuevo estado "Images Pending" si es  exitoso queda en "Draft completed".

El botón de sincronizar imágenes no debe bloquear los demás botones de sincronizar drafts, de  ser posible implementar un timeout para cancelar el envío de  las imágenes y permitir al usuario reintentar el mismo.

Caso 2 Encuesta sin imágenes: Aparecerá solo un botón para guardar la encuesta la sincronización será solo para un draft a la vez.

Obs.: 
1- Take out automatic sync for drafts
2- Leave automatic sync for priorities

Para agregar imágenes a un snapshot  se debe usar este endpoint:

```
  axios({
    method: 'post',
    url: `${url[user.env]}/graphql`,
    headers: {
      Authorization: `Bearer ${user.token}`
    },
    data: JSON.stringify({
      query:
        'mutation updateSnapshotPictures($snapshot: SnapshotUpdateModelInput) {updateSnapshotPictures(snapshot: $snapshot){successful}}',
      variables: {
        snapshot: {
          id: snapshotId,
          pictures: pictures
        }
      }
    })
  });

**Comment by JDelPuerto** [comment]
Todas las sinrcronizaciones serán manuales con este cambio, probar los siguientes casos tanto de manera online como offline:
1- Encuesta simple sin imágenes.
2- Encuesta con imágenes ( será necesario sincronizar primero la encuesta y luego las imágenes)  mediante dos botones distintos,  el botón de  sincronización de imágenes  no bloqueará el botón de sincraniación de encuestas.

Obs. para las pruebas utilizar al menos 3 drafts pendientes

**Comment by Auxi9** [comment]
el boton se podria alinear a los botones ? creo que quedaría mejor 
![Screenshot_2021-03-03-17-46-56.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/6b0a1246-cf7d-4024-8d31-32580a09a2d1)

**Comment by aprojas** [comment]
The buttons continue to appear even though I am offline, in the latest ITT version 1.19.0 
@JDelPuerto
