### ISSUE TITLE
Download drafts in sync tab

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1450]
Remove download button form the dashboard and add in the sync tab, it should only  be visible if  the user has  drafts  pending or with error status. And should only download  pending drafts and  drafts with errors.

Pre-process all drafts before downloading them inside try - catch statements

**Comment by aprojas** [comment]
Let's change the description into "Download survey data" instead of "Download JSON" because it could be confusing for many users.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/1c9fe01b-6130-41d0-930e-9ae88810cb54)
