### ISSUE TITLE
Research ways of compressing images 

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1451]
We need to implement client side compression

**Comment by JDelPuerto** [comment]
Este proceso es invisible para el usuario pero se puede testear sincronizando imágenes y luego descargando las mismas desde la página web y comparando los pesos

**Comment by Auxi9** [comment]
Desde el sansumg J1 ace, no comprime supongo porque el celular ya es de baja gama. ![Screenshot_2021-03-03-12-15-59.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/f8892303-9512-4495-b678-244834acc1c2)![Selection_499.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/99acd020-061e-4f6c-9231-444c520a6309)

**Comment by JDelPuerto** [comment]
Veo que las dimensiones de la imágenes son grandes, podés bajar la resolución de la imágen en tu teléfono y probar de vuelta @Auxi9
