### ISSUE TITLE
Adjust priorities funcionality

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1452]
- Adjust the way the priorities will be sent (automatic sync or not?)

**Comment by JDelPuerto** [comment]
Para probar esto tomar esto encuestas completando  la parte del semáforo con colores amarillos y rojos, probar ambos cosas de manera online y offline.

El primer caso sería para un draft pendiente, entrar al tab de "stoplight" donde aparecera el botón para agregar prioridades al sincronizar dicho draft tanto en la web como en la app( luego de actualizar el listado de familias) se podrá verificar que se haya guardado la prioridad

El segundo caso sería agregar prioridades a un familia ya sincronizada, se debe ir al listado de familias seleccionar una familia   e ir al tab de "stoplights" o "semáforo" donde será visible el botón, si este tab no aparece se debe a que la familia se saltó la parte del semáforo

**Comment by Auxi9** [comment]
No aparece el icono en sincronizacion cuando hay encuestas pendientes @Guillecaba @aprojas
