### ISSUE TITLE
Show signature in family's pending draft

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1467]
As we show the images in the pending draft, we also have to add the signature of the family there.

**Comment by Auxi9** [comment]
Escribi Auxi, se corta la firma @Guillecaba @aprojas . Esto lo probe con el samsung J1 

![Screenshot_2021-03-17-14-49-32.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/1755c3ac-340d-4266-9786-bbe735ee13c3)
