### ISSUE TITLE
Refactor of date formats

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1468]
Date locale it's hardcoded in several places, I think we can set date locale in just one site like we do it on the web app. This will make adding other languages easier for us in the future and we would erase redundant code and imports

**Comment by Guillecaba** [comment]
Esto mas bien es un cambio en el codigo, no se ve a simple vista, pero es importante verificar que los lugares donde existan fechas no tengan problemas de traduccion

**Comment by aprojas** [comment]
No se si tiene que ver con este issue, pero entrando a todos los perfiles de familia con mi user: t/anatest, ir al tab de Stoplights, muestran como que todos se crearon el 6 de abril 2021. Que es la fecha de HOY.

@Guillecaba 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/9c21a7cb-7d43-4552-ad31-cad11af15e39)

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/52308220-c2a4-49ea-9041-57198ea8ca28)

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/c5508d66-f20c-4fef-b7cb-8e68c98438b8)
