### ISSUE TITLE
Allow facilitator user without survey to login

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1484]
Add a modal to indicate that user has no surveys linked

**Comment by Guillecaba** [comment]
Si se va a probar con el usuario guille de testing, primero se ingresa a la web y uno se dirige a la pantalla de encuestas, en donde uno se asegura que la organizacion interactive test no tenga ninguna encuesta asignada, luego de esto uno logea en la app, y debe permitir llegar al dashboard sin tener ninguna encuesta asignada y si se quiere tomar una encuesta debe haber un mensaje que no tenes encuestas asignadas
