### ISSUE TITLE
Bug showing family members 

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1488]

**Comment by aprojas** [comment]
It is not showing the gender or documentType of the main family member from family `Andrea Belen Cisneros Serafini`.
And it does not show the gender of the other members. @Guillecaba 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/db1f8d73-362c-42e1-92ce-90aad476c2c5)

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/e73c1aab-dd61-47a7-81a7-b579ef8847c3)

Is this normal? Maybe there is no survey attached anymore?
