### ISSUE TITLE
Button "Take stoplight" goes to the draft

### ISSUE THREAD

**Issue by diegotorrespy** [FundacionParaguaya/stoplight-mobile#1496]
### Problem
The "Begin Stoplight survey" button instead of going to the survey selector goes to the draft that previously I was seeing.

The next video show how to reproduce the bug
https://images.zenhubusercontent.com/161184202/d6d4108c-eddb-44da-9567-2a0082a75b47/svid_20210414_120347_1.mp4

**Comment by Auxi9** [comment]
Esto no esta funcionando @Guillecaba
