### ISSUE TITLE
Internal changes in the flow of pdf & json download

### ISSUE THREAD

**Issue by Guillecaba** [FundacionParaguaya/stoplight-mobile#1509]
create psp folder if download folder does not exist and show warning modal

**Comment by Guillecaba** [comment]
Para probar es necesario no contar con la carpeta Download, lo que va a ocurre es que se debe crear otra carpeta llamada Psp, donde se va a guardar los pdf y los json, se debe mostrar un modal donde diga que se esta guardando en la carpeta psp

**Comment by aprojas** [comment]
To test: change the name of the "Download" folder.

**Comment by Auxi9** [comment]
Asi queda el mensaje @aprojas 

 ![20210423112145_Screenshot_2021-04-23-11-12-10-811_com.povertystoplightapp.jpg](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/27b63939-322d-4ba8-9f1e-a814a38756c0)
