### ISSUE TITLE
List interventions per family

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-mobile#1517]
Add a new tab for synced families only.

Add pending tag  as we do for priorities.

To show details an intervention must be synced we will show all details in a separate view just like family members are displayed

**Comment by Guillecaba** [comment]
Se agrego negrita a los títulos de los inputs al ingresar al detalle de una intervención.
Se acortaron los mensajes en los label de sincronizacion en el listado de intervenciones.
Si se tiene intervenciones no sincronizadas y se quiere hacer logout, debe salir modal de advertencia.
Al ver detalle los indicadores en el multiselect deben contar con el color que el encuestador selecciono al tomar la encuesta.
