### ISSUE TITLE
Send default location for families without coordinates

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1540]
To make sure that we always send some coordinates to the server we should check the coordinates during draft's pre-processing,  currently some drafts are being send with empty string or in rare cases with "0 ; 0" that  shouldn't happen either

**Comment by Auxi9** [comment]
Caso de prueba:
Deshabilite el gps y la ubicacion del celular
Tome la encuesta de manera offline 
En la pagina de la ubicacion se visualizaba "No podemos localizarte"
Prendia el wifi antes de sincronizar 
La encuesta queda en estado de ERROR

Guillermo volvera a verificar
