### ISSUE TITLE
Sync Screen  - Errors

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-mobile#281]
![Screen Shot 2019-01-15 at 11.51.33.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/cbdbbedb-2fa9-45c5-9d5c-eab98ef21940)

![Screen Shot 2019-01-15 at 11.53.44.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/b72c078d-72d7-44e4-89b5-a831dd757db1)

**Comment by stacylorraineprendeville** [comment]
How would a client correct the error - What should they do?

**Comment by Danman7** [comment]
We should discuss this further.

**Comment by Danman7** [comment]
We need appropriate error messages from the server to implement this.

**Comment by Danman7** [comment]
@stacylorraineprendeville We now might have sufficient error messaging, I need to check.

**Comment by stacylorraineprendeville** [comment]
@Danman7 Can you let me know the possibilities of what the error messages are?

**Comment by stacylorraineprendeville** [comment]
I have re-opened this ticket as it does not find its way into the product.
I have added a blocker for the new ticket

https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/mentorapp/281
