### ISSUE TITLE
Search lens in the country section

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#375]
Include a Search "lens" or "magnifying glass" icon in the country field. Now, you have to search manually in a long list of countries. It helps that it is predetermined from where the survey is. However, if the person has another nationality, that person would have to manually search for the correct country. This is found in many apps, you start writing your country, and the dropdown options start to appear.

**Comment by Danman7** [comment]
This now includes search on all dropdowns, if we ever get to such a thing.
