### ISSUE TITLE
Optional addition of Questions into the Poverty Stoplight section of the Survey

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-mobile#429]
As a client
I want to be able to add additional questions to the poverty stoplight section within the primary participant page

Example
Additional Phone Number
Citizen Status

**Comment by pA1nD** [comment]
Those questions would be either part of the socio economic page or we create a new category of questions (additionalFamilyQuestions). They should be linked into the core family questions via hooks.

e.g. Additional Phone number (Setting: Show after Question: Phone number).

**Comment by stacylorraineprendeville** [comment]
BIG Job - More than 2 sprints - Should be a flexible solution
Stacy to spec with replicas

**Comment by Danman7** [comment]
This would go into `surveyConfig` which we can implement into the forms.

@stacylorraineprendeville I guess this is for primary participant and possibly other family members. Am I right?

**Comment by stacylorraineprendeville** [comment]
@Danman7 Yes - How long would it take - I guess we need to make the request per survey and it is you and diego - correct?

**Comment by Danman7** [comment]
I will set an example structure here.

**Comment by stacylorraineprendeville** [comment]
@Danman7 this needs to be groomed asap

**Comment by Danman7** [comment]
We will discuss this with @javierpf @diegotorrespy

**Comment by aprojas** [comment]
We arrived to the conclusion and decision that this is not possible to include.
If they want to add new questions that relate to the Primary Participant screen, they can include these in the first screen of the Socioeconomic section. 
@stacylorraineprendeville 

If I remember correctly, this was a request made by Geco, now I can tell Replicas that it will not be possible so they can communicate it to the partner.

**Comment by stacylorraineprendeville** [comment]
We did not arrive at the decision that this was impossible.
We offered the client to add these questions to socio economic in the interim.
This was already told to the client months ago and they are working in the field.

This issue is to understand if we can offer this in the future - irrespective of the client request. So it stays open.
