### ISSUE TITLE
Making mandatory optional poverty stoplight questions ;)

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-mobile#447]
Birth dates on Family Members are enforced as included questions BUT these are NOT mandatory.

Clients are now creating Conditional Logic based on Ages - In those surveys it would make sense for the Birth dates of additional family members to be mandatory.

Can this be optionally enforced as mandatory in the front end on a per survey basis?

Check the backend specification [here](  https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/fp-psp-server/722) . Right now NO survey  has data  for this but we can add it for testing purposes in Testing Fupa survey

## Additional context
in the front end add an empty string for all fields that are mandatory for default.

**Comment by stacylorraineprendeville** [comment]
@pA1nD @danicricco 
Please review

@diegotorrespy can you write your proposed solution here

**Comment by pA1nD** [comment]
This is possible.

General idea:
(1) Add another Key to the ConfigSettings that makes this mandatory.
(2) done.

**Comment by diegotorrespy** [comment]
@stacylorraineprendeville @pA1nD @danicricco @JDelPuerto 

What Bjorn said is a good proposal for the back end side and it is not hard to implement. 

**Steps to do in the back end:**
1. Create the `mandatory` column in the surveyConfig section.
2. For all existence records (documentType, gender, etc) the default value will be true.
3. Make this available in the graphql service.

**Comment by Danman7** [comment]
@diegotorrespy Do we have an issue at the backend for this?

**Comment by diegotorrespy** [comment]
@Danman7 

This is the issue for the back end in case that we need to implement it for the next sprints:
https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/722

**Comment by JDelPuerto** [comment]
@Danman7  This issue is unblocked now, check  https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/722. Right now NO survey  has data  for this but we can add it for testing purposes in Testing Fupa survey
