### ISSUE TITLE
Skipped Questions and Opportunities to Answer later

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-mobile#467]
A user should be able to answer a skipped question RETROSPECTIVELY.

When a user accesses the family list and views a life-map we should give the user the opportunity to answer the question at a later date - hours or months in the future. Some questions are sensitive and perhaps people do not want to answer in the moment - The poverty stoplight wants to gather as much data as possible. It is probable a mentor revisits a family a month later and the family is ready to answer something that was previously skipped.
This functionality is already available in draft mode - This task now concerns with adding this to completed drafts.

![Screen Shot 2019-04-02 at 11.24.13.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/1e68b2df-672f-42d5-8412-0351fb8f3a7b)

**Comment by stacylorraineprendeville** [comment]
@Danman7 this is one of the tasks we need to talk about in our sessions - It is the same as priorities where we want to give the user the chance to add later. As well we also want the opportunity to edit family details later.....so these issues will have a common theme and we should consider how we handle pending sync and sync error at the same time as understanding how we work with the back end.

**Comment by Danman7** [comment]
@stacylorraineprendeville @diegotorrespy We need an endpoint for this so we can post individual updates to portions of snapshots. We should discuss.
