### ISSUE TITLE
Install Session Replay in Free Trial on Web App

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-mobile#845]
## Problem

As a UXér I have now idea how people are integrating with the App and no time to make usability tests - currently!
I´d like to have some session replay of what people are doing in the App.

## Solution

Could you see how much time is required for the installation of https://uxcam.com/ of something similar -even the 14 day trial would give some sessions for us to review and be worthwhile.

**Comment by Danman7** [comment]
I will put extra time here for testing since we are not familiar with such solutions.

@stacylorraineprendeville We would like to use the N day trial during a period when we know the web app is heavily used.
