### ISSUE TITLE
Achievements and Round 1

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-mobile#858]
### Problem
The original spec received from the FP team was incorrect. Achievements CANNOT be added in Round 1- This was given as part of the specification because retaking was not possible.

### Solution
Remove achievements from round 1 at launch of retaking
Achievements are only possible when an indicator from round 1 has progress in round 2.
This progress could be red to yellow or yellow to red.

The indicator "achieved" assignment is automatic.

**Comment by Danman7** [comment]
We already know that the user is retaking based on his navigation choices so we can disable achievements if he is not. @vasildimitroffhristoff Let's discuss this when resuming work on retaking.
